# Generated by Django 4.0.5 on 2022-06-08 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bookName', models.CharField(blank=True, max_length=30, null=True)),
                ('bookAuthor', models.CharField(max_length=20)),
                ('bookType', models.IntegerField(default=1)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
