# Generated by Django 4.0.5 on 2022-06-13 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_loan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='id',
        ),
        migrations.AddField(
            model_name='loan',
            name='_id',
            field=models.AutoField(default='1', editable=False, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
