# Generated by Django 4.0.5 on 2022-06-13 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_loan__id_loan_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='userID',
            new_name='user',
        ),
    ]
