# Generated by Django 4.0.5 on 2022-06-13 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_userid_loan_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='user',
            new_name='userID',
        ),
    ]
